# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Snapshot Test Case Demo' do

end

target 'Snapshot Test Case DemoTests' do

pod 'FBSnapshotTestCase'

end

